### ISSUE TITLE
Ensure output packages are reproducible over time

### ISSUE THREAD

**Issue by sathyanarays** [vmware-tanzu/build-tooling-for-integrations#20]
**Describe the bug**
Given a commit ID or TAG, the output of `make all` should be identical over time. In the current state of Makefile, there are references to the image `quay.io/hyayiv/packaging:latest` and the executables inside this image are being used to build the packages, push them to OCI registry, etc.,. The underlying image pointed by `quay.io/hyayiv/packaging:latest` is subject to change over time. So, it's better use a specific tag instead of latest.

**To Reproduce**
- Run `make all`
- Slightly change the packaging behavior, build the image `quay.io/hyayiv/packaging:latest` and push
- Run `make all` again
- The outputs produced in the first step and third step might be different.

**Expected behavior**
Same version of `Makefile` should produce identical outputs on running `make all`. The output should not be dynamic and not dependent on external factors.

**Screenshots**
N/A

**Comment by yharish991** [comment]
this issue has been addressed with this pr https://github.com/vmware-tanzu/build-tooling-for-integrations/pull/34, feel free to open this issue if you have any questions/concerns
