### ISSUE TITLE
Add a release workflow

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/build-tooling-for-integrations#23]
**Describe the solution you'd like**

Add a GitHub workflow action that automates the release process. 

When a tag is created, the docker images for the Dockerfiles in the `package-tooling-image` and root directories should be created and pushed to `ghcr.io/vmware-tanzu`.

**Comment by yharish991** [comment]
This can be closed as the release workflow was added with this pr https://github.com/vmware-tanzu/build-tooling-for-integrations/pull/34
